// Concatenates src/host/*.jsx (name order) into dist/cep/jsx/index.jsx and
// verifies the result parses as ES3, the language level of After Effects' ExtendScript.
import { readFileSync, readdirSync, mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "acorn";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const srcDir = join(root, "src/host");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));

export function bundleHost() {
  const files = readdirSync(srcDir).filter((f) => f.endsWith(".jsx")).sort();
  const parts = files.map((f) => `// ---- ${f} ----\n${readFileSync(join(srcDir, f), "utf8")}`);
  const code =
    `// Master Edit Suite host layer v${pkg.version}. Generated by scripts/build-host.mjs; do not edit.\n` +
    parts.join("\n");
  // ES3 has no "let", arrow functions or trailing commas, and reserves Java-style
  // words (short, int, class, static, ...) that After Effects refuses to run.
  // acorn allows those in ES3 mode unless allowReserved is false.
  parse(code, { ecmaVersion: 3, sourceType: "script", allowReserved: false });
  return code.replace(/M\.VERSION = "[^"]*"/, `M.VERSION = "${pkg.version}"`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const out = join(root, "dist/cep/jsx/index.jsx");
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, bundleHost());
  console.log(`host: wrote ${out}`);
}
